# for testing - not a real secret
login_secret: 'ffffffffffffffffffffffffffffffffffffffffffffffff'

# Disabled for testing
# Serve web app from ./static
serve_static: 'static'
port: 8000 # (default for uvicorn)

# diabled for testing
# location of db, logs
#base_path: '/data'

# Regions returned by /api/data/regions
regions:
  - key: localhost
    name: 'Local Agent'
    host: 'http://localhost'
    token: 'test_token'

loginservers:
  - name: localhost
    url: localhost

status_polling_rate_secs: 30

