# for testing - not a real secret
login_secret: 'ffffffffffffffffffffffffffffffffffffffffffffffff'

# Disabled for testing
# Serve web app from ./static
#serve_static: 'static'
port: 8000 # (default for uvicorn)

# diabled for testing
# location of db, logs
#base_path: '/data/api'

# Regions
regions:
  - key: localhost
    name: 'Local Agent'
    host: 'http://localhost'
    token: 'test_token'
  # - key: central_us
  #   name: 'NA Central'
  #   host: 'http://central'
  #   token: 'central_token'
  # - key: west_us
  #   name: 'NA West'
  #   host: 'http://central'
  #   token: 'west_token'
  # - key: central_eu
  #   name: 'EU Central'
  #   host: 'http://eu_central_url'
  #   token: ''

# how frequently to poll the agent for status in each region
status_polling_rate_secs: 300

loginservers:
  - name: Server
    url: server.local
  - name: localhost
    url: localhost