# for testing - not a real secret
login_secret: '21fbbcb4eeb2a5ad60d11436fcc92b506b6f4c3f349f604c'

# Disabled for testing
# Serve web app from ./static
#serve_static: 'static'
port: 8000 # (default for uvicorn)

# diabled for testing
# location of db, logs
#base_path: '/data'

# Regions returned by /api/data/regions
regions:
  central_us: 'NA Central'
  east_us: 'NA East'
  west_us: 'NA West'
  east_au: 'Australia East'

host_manager:
  port: 8999
  
  # mapping from region key to hostname
  # host_manager iterates over this list so missing or extra regions wont cause errors
  nodes:
    central_us: 'localhost'
    east_us: 'localhost'