# for testing - not a real secret
login_secret: 'ffffffffffffffffffffffffffffffffffffffffffffffff'

# Disabled for testing
# Serve web app from ./static
serve_static: 'static'
port: 8000 # (default for uvicorn)

# diabled for testing
# location of db, logs
#base_path: '/data'

# Regions returned by /api/data/regions
regions:
  central_us: 'NA Central'
  east_us: 'NA East'
  west_us: 'NA West'
  east_au: 'Australia East'

host_manager:
  port: 8999

  # for testing - not a real auth key
  # should match agent/config.yaml
  auth_key: '9c22a375263b971e254c'
  
  # mapping from region key to hostname
  # host_manager iterates over this list so missing or extra regions wont cause errors
  nodes:
    local: 'localhost'